**Q1**

In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
import re

In [3]:
base_url = "https://books.toscrape.com/"

# fetch the homepage
response = requests.get(base_url + "index.html")
soup = BeautifulSoup(response.text, "html.parser")

target_categories = ["Travel", "Romance", "Religion", "Poetry"]

category_links = {}

sidebar = soup.find('div', class_='side_categories')
category_tags = sidebar.find_all('a')

for tag in category_tags:
    cat_name = tag.text.strip()
    if cat_name in target_categories:
        link = tag['href']
        category_links[cat_name] = base_url + link

print("found the following category links:")
for name, link in category_links.items():
    print(f"{name}: {link}")

found the following category links:
Travel: https://books.toscrape.com/catalogue/category/books/travel_2/index.html
Romance: https://books.toscrape.com/catalogue/category/books/romance_8/index.html
Religion: https://books.toscrape.com/catalogue/category/books/religion_12/index.html
Poetry: https://books.toscrape.com/catalogue/category/books/poetry_23/index.html

In [5]:
# helper function to convert text star ratings to numbers
def convert_rating(class_list):
    mapping = {'One': 1, 'Two': 2, 'Three': 3, 'Four': 4, 'Five': 5}
    for cls in class_list:
        if cls in mapping:
            return mapping[cls]
    return 0

scraped_books = {} # key: book title, value: dictionary of book details

for cat_name, cat_url in category_links.items():
    print(f"\n Scraping Category: {cat_name} ")
    current_page_url = cat_url

    actual_books_scraped = 0
    expected_total = 0

    while True:
        # fetch the current listing page
        response = requests.get(current_page_url)
        soup = BeautifulSoup(response.text, "html.parser")

        #expected total results count
        if expected_total == 0:
            total_tag = soup.select_one('.form-horizontal strong')
            if total_tag:
                expected_total = int(total_tag.text)
                print(f"expected total books in {cat_name}: {expected_total}")

        #extract all books on the current page
        books_on_page = soup.find_all('article', class_='product_pod')

        for book in books_on_page:

            title = book.find('h3').find('a')['title'].strip()

            if title in scraped_books:
                actual_books_scraped += 1
                continue

            # construct the absolute URL for the individual product page
            book_rel_link = book.find('h3').find('a')['href']
            clean_link = book_rel_link.replace('../../../', '')
            book_url = f"https://books.toscrape.com/catalogue/{clean_link}"

            book_resp = requests.get(book_url)
            book_soup = BeautifulSoup(book_resp.text, "html.parser")

            price = book_soup.find('p', class_='price_color').text.strip()

            availability = book_soup.find('p', class_='instock availability').text.strip()

            star_tag = book_soup.find('p', class_='star-rating')
            star_rating = convert_rating(star_tag['class']) if star_tag else 0

            upc = ""
            upc_th = book_soup.find('th', string='UPC')
            if upc_th:
                upc = upc_th.find_next_sibling('td').text.strip()

            description = ""
            desc_div = book_soup.find('div', id='product_description')
            if desc_div:
                description = desc_div.find_next_sibling('p').text.strip()


            scraped_books[title] = {
                'Title': title,
                'Price': price,
                'In-stock availability text': availability,
                'Star rating': star_rating,
                'UPC': upc,
                'Product description': description,
                'Category': cat_name
            }
            actual_books_scraped += 1

        #handle pagination
        next_btn = soup.find('li', class_='next')
        if next_btn:
            next_page_rel = next_btn.find('a')['href']
            current_page_url = current_page_url.rsplit('/', 1)[0] + '/' + next_page_rel
        else:
            break

    # comparing expected vs actual
    print(f"Validation for {cat_name}:")
    if actual_books_scraped == expected_total:
        print(f"PASS ^^ : Scraped {actual_books_scraped} books, exactly matching the expected {expected_total}.")
    else:
        print(f"FAIL :( : Scraped {actual_books_scraped} books, but expected {expected_total}.")

 Scraping Category: Travel
expected total books in Travel: 11
Validation for Travel:
PASS ^^ : Scraped 11 books, exactly matching the expected 11.

 Scraping Category: Romance
expected total books in Romance: 35
Validation for Romance:
PASS ^^ : Scraped 35 books, exactly matching the expected 35.

 Scraping Category: Religion
expected total books in Religion: 7
Validation for Religion:
PASS ^^ : Scraped 7 books, exactly matching the expected 7.

 Scraping Category: Poetry
expected total books in Poetry: 19
Validation for Poetry:
PASS ^^ : Scraped 19 books, exactly matching the expected 19.

In [6]:
books_list = list(scraped_books.values())

df_static = pd.DataFrame(books_list)

csv_filename = '23L_2503_versionB_static_books.csv'
df_static.to_csv(csv_filename, index=False)

print(f"Data saved to {csv_filename}")

df_static.head()

Data saved to 23L_2503_versionB_static_books.csv

,Title,Price,In-stock availability text,Star rating,UPC,Product description,Category
0,It's Only the Himalayas,Â£45.17,In stock (19 available),2,a22124811bfa8350,"âWherever you go, whatever you do, just . . ...",Travel
1,Full Moon over Noahâs Ark: An Odyssey to Mou...,Â£49.43,In stock (15 available),4,ce60436f52c5ee68,Acclaimed travel writer Rick Antonson sets his...,Travel
2,See America: A Celebration of Our National Par...,Â£48.87,In stock (14 available),3,f9705c362f070608,To coincide with the 2016 centennial anniversa...,Travel
3,Vagabonding: An Uncommon Guide to the Art of L...,Â£36.94,In stock (8 available),2,1809259a5a5f1d8d,With a new foreword by Tim Ferriss â¢Thereâ...,Travel
4,Under the Tuscan Sun,Â£37.33,In stock (7 available),3,a94350ee74deaa07,A CLASSIC FROM THE BESTSELLING AUTHOR OF UNDER...,Travel

**Q2**

In [7]:
test_resp = requests.get("https://quotes.toscrape.com/scroll")
test_soup = BeautifulSoup(test_resp.text, "html.parser")
quotes_found = test_soup.find_all('div', class_='quote')
print(f"quotes found using plain requests: {len(quotes_found)}")

quotes found using plain requests: 0

In [10]:
# Install Google Chrome
!wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
!dpkg -i google-chrome-stable_current_amd64.deb
!apt-get -f install -y

# Install Selenium and ChromeDriver Manager
!pip install selenium webdriver-manager

--2026-09-12 16:11:38--  https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
Resolving dl.google.com (dl.google.com)... 142.250.152.93, 142.250.152.136, 142.250.152.190, ...
Connecting to dl.google.com (dl.google.com)|142.250.152.93|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 141931876 (135M) [application/x-debian-package]
Saving to: ‘google-chrome-stable_current_amd64.deb’

google-chrome-stabl 100%[===================>] 135.36M   137MB/s    in 1.0s

2026-09-12 16:11:39 (137 MB/s) - ‘google-chrome-stable_current_amd64.deb’ saved [141931876/141931876]

Selecting previously unselected package google-chrome-stable.
(Reading database ... 122797 files and directories currently installed.)
Preparing to unpack google-chrome-stable_current_amd64.deb ...
Unpacking google-chrome-stable (153.0.8010.36-1) ...
dpkg: dependency problems prevent configuration of google-chrome-stable:
 google-chrome-stable depends on libatk-bridge2.0-0 (>= 2.5.3); however:
  Package libatk-bridge2.0-0 is not installed.
 google-chrome-stable depends on libatk1.0-0 (>= 2.11.90); however:
  Package libatk1.0-0 is not installed.
 google-chrome-stable depends on libatspi2.0-0 (>= 2.9.90); however:
  Package libatspi2.0-0 is not installed.
 google-chrome-stable depends on libxcomposite1 (>= 1:0.4.4-1); however:
  Package libxcomposite1 is not installed.

dpkg: error processing package google-chrome-stable (--install):
 dependency problems - leaving unconfigured
Processing triggers for man-db (2.12.0-4build2) ...
Errors were encountered while processing:
 google-chrome-stable
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Correcting dependencies... Done
The following additional packages will be installed:
  at-spi2-common at-spi2-core gsettings-desktop-schemas libatk-bridge2.0-0t64
  libatk1.0-0t64 libatspi2.0-0t64 libxcomposite1 libxtst6 session-migration
The following NEW packages will be installed:
  at-spi2-common at-spi2-core gsettings-desktop-schemas libatk-bridge2.0-0t64
  libatk1.0-0t64 libatspi2.0-0t64 libxcomposite1 libxtst6 session-migration
0 upgraded, 9 newly installed, 0 to remove and 11 not upgraded.
1 not fully installed or removed.
Need to get 331 kB of archives.
After this operation, 1,443 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu noble/main amd64 at-spi2-common all 2.52.0-1build1 [8,674 B]
Get:2 http://archive.ubuntu.com/ubuntu noble/main amd64 libatk1.0-0t64 amd64 2.52.0-1build1 [55.3 kB]
Get:3 http://archive.ubuntu.com/ubuntu noble/main amd64 libatspi2.0-0t64 amd64 2.52.0-1build1 [80.5 kB]
Get:4 http://archive.ubuntu.com/ubuntu noble/main amd64 libatk-bridge2.0-0t64 amd64 2.52.0-1build1 [66.0 kB]
Get:5 http://archive.ubuntu.com/ubuntu noble/main amd64 libxcomposite1 amd64 1:0.4.5-1build3 [6,320 B]
Get:6 http://archive.ubuntu.com/ubuntu noble/main amd64 libxtst6 amd64 2:1.2.3-1.1build1 [12.6 kB]
Get:7 http://archive.ubuntu.com/ubuntu noble/main amd64 session-migration amd64 0.3.9build1 [9,034 B]
Get:8 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 gsettings-desktop-schemas all 46.1-0ubuntu1 [35.6 kB]
Get:9 http://archive.ubuntu.com/ubuntu noble/main amd64 at-spi2-core amd64 2.52.0-1build1 [56.6 kB]
Fetched 331 kB in 1s (314 kB/s)
Selecting previously unselected package at-spi2-common.
(Reading database ... 123077 files and directories currently installed.)
Preparing to unpack .../0-at-spi2-common_2.52.0-1build1_all.deb ...
Unpacking at-spi2-common (2.52.0-1build1) ...
Selecting previously unselected package libatk1.0-0t64:amd64.
Preparing to unpack .../1-libatk1.0-0t64_2.52.0-1build1_amd64.deb ...
Unpacking libatk1.0-0t64:amd64 (2.52.0-1build1) ...
Selecting previously unselected package libatspi2.0-0t64:amd64.
Preparing to unpack .../2-libatspi2.0-0t64_2.52.0-1build1_amd64.deb ...
Unpacking libatspi2.0-0t64:amd64 (2.52.0-1build1) ...
Selecting previously unselected package libatk-bridge2.0-0t64:amd64.
Preparing to unpack .../3-libatk-bridge2.0-0t64_2.52.0-1build1_amd64.deb ...
Unpacking libatk-bridge2.0-0t64:amd64 (2.52.0-1build1) ...
Selecting previously unselected package libxcomposite1:amd64.
Preparing to unpack .../4-libxcomposite1_1%3a0.4.5-1build3_amd64.deb ...
Unpacking libxcomposite1:amd64 (1:0.4.5-1build3) ...
Selecting previously unselected package libxtst6:amd64.
Preparing to unpack .../5-libxtst6_2%3a1.2.3-1.1build1_amd64.deb ...
Unpacking libxtst6:amd64 (2:1.2.3-1.1build1) ...
Selecting previously unselected package session-migration.
Preparing to unpack .../6-session-migration_0.3.9build1_amd64.deb ...
Unpacking session-migration (0.3.9build1) ...
Selecting previously unselected package gsettings-desktop-schemas.
Preparing to unpack .../7-gsettings-desktop-schemas_46.1-0ubuntu1_all.deb ...
Unpacking gsettings-desktop-schemas (46.1-0ubuntu1) ...
Selecting previously unselected package at-spi2-core.
Preparing to unpack .../8-at-spi2-core_2.52.0-1build1_amd64.deb ...
Unpacking at-spi2-core (2.52.0-1build1) ...
Setting up session-migration (0.3.9build1) ...
Created symlink /etc/systemd/user/graphical-session-pre.target.wants/session-migration.service → /usr/lib/systemd/user/session-migration.service.
Setting up libxtst6:amd64 (2:1.2.3-1.1build1) ...
Setting up libatspi2.0-0t64:amd64 (2.52.0-1build1) ...
Setting up at-spi2-common (2.52.0-1build1) ...
Setting up libxcomposite1:amd64 (1:0.4.5-1build3) ...
Setting up gsettings-desktop-schemas (46.1-0ubuntu1) ...
Setting up libatk1.0-0t64:amd64 (2.52.0-1build1) ...
Setting up libatk-bridge2.0-0t64:amd64 (2.52.0-1build1) ...
Setting up google-chrome-stable (153.0.8010.36-1) ...
update-alternatives: using /usr/bin/google-chrome-stable to provide /usr/bin/x-www-browser (x-www-browser) in auto mode
update-alternatives: using /usr/bin/google-chrome-stable to provide /usr/bin/gnome-www-browser (gnome-www-browser) in auto mode
update-alternatives: using /usr/bin/google-chrome-stable to provide /usr/bin/google-chrome (google-chrome) in auto mode
Processing triggers for libc-bin (2.39-0ubuntu8.8) ...
/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

Processing triggers for man-db (2.12.0-4build2) ...
Processing triggers for libglib2.0-0t64:amd64 (2.80.0-6ubuntu3.8) ...
Setting up at-spi2-core (2.52.0-1build1) ...
Collecting selenium
  Downloading selenium-4.49.0-py3-none-any.whl.metadata (7.4 kB)
Collecting webdriver-manager
  Downloading webdriver_manager-4.1.2-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: certifi>=2026.2.25 in /usr/local/lib/python3.13/dist-packages (from selenium) (2026.7.22)
Collecting trio<1.0,>=0.31.0 (from selenium)
  Downloading trio-0.34.0-py3-none-any.whl.metadata (8.5 kB)
Collecting trio-websocket<1.0,>=0.12.2 (from selenium)
  Downloading trio_websocket-0.12.2-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: typing_extensions<5.0,>=4.15.0 in /usr/local/lib/python3.13/dist-packages (from selenium) (4.16.0)
Collecting urllib3<3.0,>=2.6.3 (from urllib3[socks]<3.0,>=2.6.3->selenium)
  Downloading urllib3-2.7.0-py3-none-any.whl.metadata (6.9 kB)
Requirement already satisfied: websocket-client<2.0,>=1.8.0 in /usr/local/lib/python3.13/dist-packages (from selenium) (1.9.2)
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (from webdriver-manager) (2.32.4)
Requirement already satisfied: python-dotenv in /usr/local/lib/python3.13/dist-packages (from webdriver-manager) (1.2.3)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from webdriver-manager) (26.3)
Requirement already satisfied: attrs>=23.2.0 in /usr/local/lib/python3.13/dist-packages (from trio<1.0,>=0.31.0->selenium) (26.1.0)
Collecting sortedcontainers (from trio<1.0,>=0.31.0->selenium)
  Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: idna in /usr/local/lib/python3.13/dist-packages (from trio<1.0,>=0.31.0->selenium) (3.19)
Collecting outcome (from trio<1.0,>=0.31.0->selenium)
  Downloading outcome-1.3.0.post0-py2.py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: sniffio>=1.3.0 in /usr/local/lib/python3.13/dist-packages (from trio<1.0,>=0.31.0->selenium) (1.3.1)
Collecting wsproto>=0.14 (from trio-websocket<1.0,>=0.12.2->selenium)
  Downloading wsproto-1.3.2-py3-none-any.whl.metadata (5.2 kB)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in /usr/local/lib/python3.13/dist-packages (from urllib3[socks]<3.0,>=2.6.3->selenium) (1.7.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests->webdriver-manager) (3.4.9)
Requirement already satisfied: h11<1,>=0.16.0 in /usr/local/lib/python3.13/dist-packages (from wsproto>=0.14->trio-websocket<1.0,>=0.12.2->selenium) (0.16.0)
Downloading selenium-4.49.0-py3-none-any.whl (11.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.8/11.8 MB 51.5 MB/s eta 0:00:00
Downloading webdriver_manager-4.1.2-py3-none-any.whl (32 kB)
Downloading trio-0.34.0-py3-none-any.whl (511 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 511.8/511.8 kB 18.8 MB/s eta 0:00:00
Downloading trio_websocket-0.12.2-py3-none-any.whl (21 kB)
Downloading urllib3-2.7.0-py3-none-any.whl (131 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.1/131.1 kB 5.7 MB/s eta 0:00:00
Downloading outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
Downloading wsproto-1.3.2-py3-none-any.whl (24 kB)
Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Installing collected packages: sortedcontainers, wsproto, urllib3, outcome, trio, webdriver-manager, trio-websocket, selenium
  Attempting uninstall: urllib3
    Found existing installation: urllib3 2.5.0
    Uninstalling urllib3-2.5.0:
      Successfully uninstalled urllib3-2.5.0
Successfully installed outcome-1.3.0.post0 selenium-4.49.0 sortedcontainers-2.4.0 trio-0.34.0 trio-websocket-0.12.2 urllib3-2.7.0 webdriver-manager-4.1.2 wsproto-1.3.2

In [1]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
import pandas as pd

In [2]:
options = webdriver.ChromeOptions()
options.add_argument('--headless')
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')

# Set up the ChromeDriver service
service = Service(ChromeDriverManager().install())
driver = webdriver.Chrome(service=service, options=options)

url = "https://quotes.toscrape.com/scroll"
driver.get(url)

scraped_quotes = {} # key: quote text, value: quote data
current_batch = 0
empty_scroll_count = 0

wait = WebDriverWait(driver, 5)#explicit wait (up to 5 seconds maximum per scroll)

print("starting dynamic scrolling..")

while True:

    quote_elements = driver.find_elements(By.CLASS_NAME, "quote") #grab all quote elements currently loaded in the DOM

    # extract data for any newly found quotes
    for element in quote_elements:
        try:
            quote_text = element.find_element(By.CLASS_NAME, "text").text

            if quote_text not in scraped_quotes:
                author = element.find_element(By.CLASS_NAME, "author").text

                tags_elements = element.find_elements(By.CLASS_NAME, "tag")
                tags_list = [t.text for t in tags_elements]

                scraped_quotes[quote_text] = {
                    'Quote text': quote_text,
                    'Author name': author,
                    'Tags': ", ".join(tags_list),
                    'Number of tags': len(tags_list),
                    'Scroll batch': current_batch
                }
        except Exception as e:
            print(f"error extracting an element: {e}")

    driver.execute_script("window.scrollTo(0, document.documentElement.scrollHeight);")

    #explicit wait to check if the number of quotes increases
    try:

        wait.until(lambda d: len(d.find_elements(By.CLASS_NAME, "quote")) > len(quote_elements))

        empty_scroll_count = 0
        current_batch += 1
        print(f"scrolled successfully. Now processing batch {current_batch}.")

    except:
        empty_scroll_count += 1
        print(f"No new content loaded. Consecutive empty scrolls: {empty_scroll_count}")

    if empty_scroll_count >= 2:
        print("Reached the absolute bottom (two consecutive empty scrolls). Done.")
        break

driver.quit()

quotes_list = list(scraped_quotes.values())
df_dynamic = pd.DataFrame(quotes_list)

csv_filename_dynamic = '23L_2503_versionB_dynamic_quotes.csv'
df_dynamic.to_csv(csv_filename_dynamic, index=False)

print(f"\nSuccess ^_^ : Extracted a total of {len(df_dynamic)} unique quotes.")
print(f"Data saved to {csv_filename_dynamic}")

df_dynamic.head()

starting dynamic scrolling..
scrolled successfully. Now processing batch 1.
scrolled successfully. Now processing batch 2.
scrolled successfully. Now processing batch 3.
scrolled successfully. Now processing batch 4.
scrolled successfully. Now processing batch 5.
scrolled successfully. Now processing batch 6.
scrolled successfully. Now processing batch 7.
scrolled successfully. Now processing batch 8.
scrolled successfully. Now processing batch 9.
No new content loaded. Consecutive empty scrolls: 1
No new content loaded. Consecutive empty scrolls: 2
Reached the absolute bottom (two consecutive empty scrolls). Done.

Success ^_^ : Extracted a total of 100 unique quotes.
Data saved to 23L_2503_versionB_dynamic_quotes.csv

,Quote text,Author name,Tags,Number of tags,Scroll batch
0,“The world as we have created it is a process ...,Albert Einstein,"change, deep-thoughts, thinking, world",4,0
1,"“It is our choices, Harry, that show what we t...",J.K. Rowling,"abilities, choices",2,0
2,“There are only two ways to live your life. On...,Albert Einstein,"inspirational, life, live, miracle, miracles",5,0
3,"“The person, be it gentleman or lady, who has ...",Jane Austen,"aliteracy, books, classic, humor",4,0
4,"“Imperfection is beauty, madness is genius and...",Marilyn Monroe,"be-yourself, inspirational",2,0

Bonus

In [3]:
!pip install playwright nest_asyncio
!playwright install
!playwright install-deps

Collecting playwright
  Downloading playwright-1.62.0-py3-none-manylinux1_x86_64.whl.metadata (3.3 kB)
Requirement already satisfied: nest_asyncio in /usr/local/lib/python3.13/dist-packages (1.6.0)
Collecting pyee<14,>=13 (from playwright)
  Downloading pyee-13.0.1-py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: greenlet<4.0.0,>=3.1.1 in /usr/local/lib/python3.13/dist-packages (from playwright) (3.5.5)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.13/dist-packages (from pyee<14,>=13->playwright) (4.16.0)
Downloading playwright-1.62.0-py3-none-manylinux1_x86_64.whl (47.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.7/47.7 MB 25.6 MB/s eta 0:00:00
Downloading pyee-13.0.1-py3-none-any.whl (15 kB)
Installing collected packages: pyee, playwright
Successfully installed playwright-1.62.0 pyee-13.0.1
Downloading Chrome for Testing 151.0.7922.34 (playwright chromium v1234) from https://cdn.playwright.dev/builds/cft/151.0.7922.34/linux64/chrome-linux64.zip
184.3 MiB [] 0% 379.7s184.3 MiB [] 0% 68.3s184.3 MiB [] 0% 42.7s184.3 MiB [] 0% 36.8s184.3 MiB [] 0% 30.7s184.3 MiB [] 0% 32.2s184.3 MiB [] 0% 28.3s184.3 MiB [] 0% 21.5s184.3 MiB [] 0% 16.2s184.3 MiB [] 1% 11.9s184.3 MiB [] 1% 9.8s184.3 MiB [] 2% 8.9s184.3 MiB [] 2% 8.8s184.3 MiB [] 2% 8.6s184.3 MiB [] 3% 8.1s184.3 MiB [] 3% 7.8s184.3 MiB [] 3% 7.7s184.3 MiB [] 3% 7.5s184.3 MiB [] 4% 7.5s184.3 MiB [] 4% 7.3s184.3 MiB [] 5% 7.3s184.3 MiB [] 5% 7.2s184.3 MiB [] 5% 7.1s184.3 MiB [] 6% 7.0s184.3 MiB [] 6% 6.9s184.3 MiB [] 6% 6.8s184.3 MiB [] 6% 7.2s184.3 MiB [] 6% 7.5s184.3 MiB [] 7% 7.6s184.3 MiB [] 7% 7.9s184.3 MiB [] 7% 8.1s184.3 MiB [] 8% 7.5s184.3 MiB [] 8% 7.1s184.3 MiB [] 9% 6.7s184.3 MiB [] 9% 6.3s184.3 MiB [] 10% 6.1s184.3 MiB [] 11% 5.9s184.3 MiB [] 11% 5.8s184.3 MiB [] 12% 5.6s184.3 MiB [] 12% 5.4s184.3 MiB [] 13% 5.3s184.3 MiB [] 13% 5.2s184.3 MiB [] 13% 5.1s184.3 MiB [] 14% 5.2s184.3 MiB [] 14% 5.1s184.3 MiB [] 15% 5.1s184.3 MiB [] 15% 5.0s184.3 MiB [] 16% 5.0s184.3 MiB [] 16% 4.9s184.3 MiB [] 17% 5.1s184.3 MiB [] 17% 5.2s184.3 MiB [] 17% 5.3s184.3 MiB [] 17% 5.4s184.3 MiB [] 17% 5.5s184.3 MiB [] 17% 5.4s184.3 MiB [] 18% 5.4s184.3 MiB [] 18% 5.3s184.3 MiB [] 19% 5.2s184.3 MiB [] 19% 5.1s184.3 MiB [] 20% 5.1s184.3 MiB [] 20% 5.0s184.3 MiB [] 21% 5.0s184.3 MiB [] 21% 4.9s184.3 MiB [] 22% 4.9s184.3 MiB [] 22% 4.8s184.3 MiB [] 23% 4.8s184.3 MiB [] 23% 4.7s184.3 MiB [] 24% 4.6s184.3 MiB [] 24% 4.7s184.3 MiB [] 24% 4.8s184.3 MiB [] 24% 4.9s184.3 MiB [] 25% 4.8s184.3 MiB [] 25% 4.7s184.3 MiB [] 26% 4.7s184.3 MiB [] 27% 4.6s184.3 MiB [] 27% 4.5s184.3 MiB [] 28% 4.4s184.3 MiB [] 28% 4.3s184.3 MiB [] 29% 4.2s184.3 MiB [] 30% 4.1s184.3 MiB [] 31% 4.0s184.3 MiB [] 31% 3.9s184.3 MiB [] 32% 3.8s184.3 MiB [] 33% 3.7s184.3 MiB [] 34% 3.6s184.3 MiB [] 34% 3.5s184.3 MiB [] 35% 3.4s184.3 MiB [] 36% 3.4s184.3 MiB [] 37% 3.3s184.3 MiB [] 37% 3.2s184.3 MiB [] 38% 3.2s184.3 MiB [] 38% 3.1s184.3 MiB [] 39% 3.1s184.3 MiB [] 40% 3.0s184.3 MiB [] 40% 2.9s184.3 MiB [] 41% 2.9s184.3 MiB [] 41% 3.0s184.3 MiB [] 42% 3.0s184.3 MiB [] 43% 2.9s184.3 MiB [] 44% 2.9s184.3 MiB [] 44% 2.8s184.3 MiB [] 45% 2.8s184.3 MiB [] 46% 2.7s184.3 MiB [] 47% 2.6s184.3 MiB [] 48% 2.6s184.3 MiB [] 48% 2.5s184.3 MiB [] 49% 2.5s184.3 MiB [] 49% 2.4s184.3 MiB [] 50% 2.4s184.3 MiB [] 50% 2.5s184.3 MiB [] 51% 2.4s184.3 MiB [] 52% 2.4s184.3 MiB [] 53% 2.3s184.3 MiB [] 54% 2.2s184.3 MiB [] 55% 2.2s184.3 MiB [] 56% 2.1s184.3 MiB [] 57% 2.0s184.3 MiB [] 58% 2.0s184.3 MiB [] 59% 1.9s184.3 MiB [] 60% 1.8s184.3 MiB [] 61% 1.8s184.3 MiB [] 62% 1.7s184.3 MiB [] 63% 1.7s184.3 MiB [] 63% 1.6s184.3 MiB [] 64% 1.6s184.3 MiB [] 65% 1.6s184.3 MiB [] 65% 1.5s184.3 MiB [] 66% 1.5s184.3 MiB [] 67% 1.5s184.3 MiB [] 68% 1.5s184.3 MiB [] 69% 1.4s184.3 MiB [] 70% 1.4s184.3 MiB [] 71% 1.3s184.3 MiB [] 72% 1.3s184.3 MiB [] 73% 1.2s184.3 MiB [] 74% 1.2s184.3 MiB [] 74% 1.1s184.3 MiB [] 75% 1.1s184.3 MiB [] 76% 1.1s184.3 MiB [] 77% 1.0s184.3 MiB [] 78% 1.0s184.3 MiB [] 79% 0.9s184.3 MiB [] 80% 0.9s184.3 MiB [] 81% 0.8s184.3 MiB [] 82% 0.8s184.3 MiB [] 83% 0.8s184.3 MiB [] 83% 0.7s184.3 MiB [] 84% 0.7s184.3 MiB [] 85% 0.7s184.3 MiB [] 85% 0.6s184.3 MiB [] 86% 0.6s184.3 MiB [] 87% 0.6s184.3 MiB [] 88% 0.5s184.3 MiB [] 89% 0.5s184.3 MiB [] 90% 0.4s184.3 MiB [] 91% 0.4s184.3 MiB [] 92% 0.4s184.3 MiB [] 92% 0.3s184.3 MiB [] 93% 0.3s184.3 MiB [] 94% 0.3s184.3 MiB [] 94% 0.2s184.3 MiB [] 95% 0.2s184.3 MiB [] 96% 0.1s184.3 MiB [] 97% 0.1s184.3 MiB [] 98% 0.1s184.3 MiB [] 99% 0.0s184.3 MiB [] 100% 0.0s
Chrome for Testing 151.0.7922.34 (playwright chromium v1234) downloaded to /root/.cache/ms-playwright/chromium-1234
Downloading Chrome Headless Shell 151.0.7922.34 (playwright chromium-headless-shell v1234) from https://cdn.playwright.dev/builds/cft/151.0.7922.34/linux64/chrome-headless-shell-linux64.zip
114.7 MiB [] 0% 0.0s114.7 MiB [] 0% 13.8s114.7 MiB [] 0% 8.8s114.7 MiB [] 0% 6.6s114.7 MiB [] 2% 3.2s114.7 MiB [] 3% 2.3s114.7 MiB [] 5% 2.0s114.7 MiB [] 6% 1.8s114.7 MiB [] 7% 1.7s114.7 MiB [] 8% 1.6s114.7 MiB [] 9% 1.5s114.7 MiB [] 11% 1.7s114.7 MiB [] 11% 1.8s114.7 MiB [] 11% 2.0s114.7 MiB [] 12% 1.9s114.7 MiB [] 13% 1.8s114.7 MiB [] 14% 1.7s114.7 MiB [] 15% 1.7s114.7 MiB [] 17% 1.6s114.7 MiB [] 18% 1.6s114.7 MiB [] 19% 1.5s114.7 MiB [] 21% 1.4s114.7 MiB [] 22% 1.4s114.7 MiB [] 23% 1.4s114.7 MiB [] 24% 1.3s114.7 MiB [] 26% 1.3s114.7 MiB [] 27% 1.2s114.7 MiB [] 28% 1.3s114.7 MiB [] 29% 1.3s114.7 MiB [] 30% 1.2s114.7 MiB [] 31% 1.3s114.7 MiB [] 32% 1.2s114.7 MiB [] 34% 1.2s114.7 MiB [] 35% 1.2s114.7 MiB [] 36% 1.2s114.7 MiB [] 37% 1.2s114.7 MiB [] 38% 1.2s114.7 MiB [] 39% 1.2s114.7 MiB [] 39% 1.3s114.7 MiB [] 40% 1.3s114.7 MiB [] 41% 1.3s114.7 MiB [] 42% 1.2s114.7 MiB [] 43% 1.2s114.7 MiB [] 45% 1.2s114.7 MiB [] 46% 1.1s114.7 MiB [] 47% 1.1s114.7 MiB [] 48% 1.1s114.7 MiB [] 49% 1.0s114.7 MiB [] 51% 1.0s114.7 MiB [] 52% 0.9s114.7 MiB [] 53% 0.9s114.7 MiB [] 54% 0.9s114.7 MiB [] 56% 0.9s114.7 MiB [] 58% 0.8s114.7 MiB [] 59% 0.8s114.7 MiB [] 61% 0.7s114.7 MiB [] 62% 0.7s114.7 MiB [] 64% 0.7s114.7 MiB [] 65% 0.6s114.7 MiB [] 66% 0.6s114.7 MiB [] 66% 0.7s114.7 MiB [] 67% 0.7s114.7 MiB [] 68% 0.7s114.7 MiB [] 69% 0.6s114.7 MiB [] 70% 0.6s114.7 MiB [] 72% 0.5s114.7 MiB [] 74% 0.5s114.7 MiB [] 75% 0.5s114.7 MiB [] 76% 0.5s114.7 MiB [] 77% 0.4s114.7 MiB [] 79% 0.4s114.7 MiB [] 80% 0.4s114.7 MiB [] 82% 0.3s114.7 MiB [] 83% 0.3s114.7 MiB [] 85% 0.3s114.7 MiB [] 86% 0.3s114.7 MiB [] 88% 0.2s114.7 MiB [] 89% 0.2s114.7 MiB [] 90% 0.2s114.7 MiB [] 91% 0.2s114.7 MiB [] 92% 0.1s114.7 MiB [] 93% 0.1s114.7 MiB [] 95% 0.1s114.7 MiB [] 97% 0.1s114.7 MiB [] 98% 0.0s114.7 MiB [] 100% 0.0s
Chrome Headless Shell 151.0.7922.34 (playwright chromium-headless-shell v1234) downloaded to /root/.cache/ms-playwright/chromium_headless_shell-1234
Downloading Firefox 153.0 (playwright firefox v1538) from https://cdn.playwright.dev/dbazure/download/playwright/builds/firefox/1538/firefox-ubuntu-24.04.zip
108.2 MiB [] 0% 0.0s108.2 MiB [] 0% 11.3s108.2 MiB [] 0% 6.8s108.2 MiB [] 1% 4.1s108.2 MiB [] 2% 3.1s108.2 MiB [] 3% 2.6s108.2 MiB [] 4% 2.2s108.2 MiB [] 5% 2.1s108.2 MiB [] 6% 2.0s108.2 MiB [] 7% 1.8s108.2 MiB [] 9% 1.6s108.2 MiB [] 10% 1.5s108.2 MiB [] 11% 1.5s108.2 MiB [] 12% 1.4s108.2 MiB [] 14% 1.4s108.2 MiB [] 14% 1.5s108.2 MiB [] 14% 1.6s108.2 MiB [] 14% 1.8s108.2 MiB [] 15% 1.7s108.2 MiB [] 17% 1.6s108.2 MiB [] 18% 1.6s108.2 MiB [] 19% 1.5s108.2 MiB [] 20% 1.5s108.2 MiB [] 21% 1.4s108.2 MiB [] 23% 1.4s108.2 MiB [] 24% 1.3s108.2 MiB [] 25% 1.4s108.2 MiB [] 26% 1.3s108.2 MiB [] 28% 1.3s108.2 MiB [] 29% 1.3s108.2 MiB [] 30% 1.2s108.2 MiB [] 32% 1.2s108.2 MiB [] 33% 1.1s108.2 MiB [] 34% 1.1s108.2 MiB [] 35% 1.1s108.2 MiB [] 37% 1.0s108.2 MiB [] 39% 1.0s108.2 MiB [] 40% 1.0s108.2 MiB [] 41% 0.9s108.2 MiB [] 42% 0.9s108.2 MiB [] 43% 0.9s108.2 MiB [] 44% 0.9s108.2 MiB [] 45% 0.9s108.2 MiB [] 46% 0.9s108.2 MiB [] 47% 0.9s108.2 MiB [] 49% 0.8s108.2 MiB [] 51% 0.8s108.2 MiB [] 52% 0.8s108.2 MiB [] 54% 0.7s108.2 MiB [] 57% 0.7s108.2 MiB [] 58% 0.6s108.2 MiB [] 60% 0.6s108.2 MiB [] 61% 0.6s108.2 MiB [] 62% 0.6s108.2 MiB [] 64% 0.5s108.2 MiB [] 65% 0.5s108.2 MiB [] 68% 0.5s108.2 MiB [] 69% 0.4s108.2 MiB [] 72% 0.4s108.2 MiB [] 74% 0.4s108.2 MiB [] 75% 0.4s108.2 MiB [] 77% 0.3s108.2 MiB [] 79% 0.3s108.2 MiB [] 81% 0.3s108.2 MiB [] 83% 0.2s108.2 MiB [] 85% 0.2s108.2 MiB [] 87% 0.2s108.2 MiB [] 89% 0.1s108.2 MiB [] 91% 0.1s108.2 MiB [] 93% 0.1s108.2 MiB [] 95% 0.1s108.2 MiB [] 96% 0.0s108.2 MiB [] 98% 0.0s108.2 MiB [] 100% 0.0s
Firefox 153.0 (playwright firefox v1538) downloaded to /root/.cache/ms-playwright/firefox-1538
Downloading WebKit 26.5 (playwright webkit v2336) from https://cdn.playwright.dev/dbazure/download/playwright/builds/webkit/2336/webkit-ubuntu-24.04.zip
102 MiB [] 0% 0.0s102 MiB [] 0% 19.6s102 MiB [] 0% 16.3s102 MiB [] 0% 12.1s102 MiB [] 0% 8.4s102 MiB [] 1% 6.0s102 MiB [] 1% 5.2s102 MiB [] 2% 4.1s102 MiB [] 3% 3.3s102 MiB [] 4% 3.1s102 MiB [] 5% 2.8s102 MiB [] 6% 2.8s102 MiB [] 7% 2.5s102 MiB [] 8% 2.3s102 MiB [] 9% 2.1s102 MiB [] 10% 2.0s102 MiB [] 12% 1.9s102 MiB [] 13% 1.8s102 MiB [] 14% 1.7s102 MiB [] 15% 1.7s102 MiB [] 15% 1.8s102 MiB [] 15% 1.9s102 MiB [] 15% 2.0s102 MiB [] 16% 2.2s102 MiB [] 16% 2.1s102 MiB [] 18% 2.0s102 MiB [] 19% 2.0s102 MiB [] 20% 1.8s102 MiB [] 21% 1.8s102 MiB [] 23% 1.7s102 MiB [] 24% 1.7s102 MiB [] 25% 1.6s102 MiB [] 26% 1.5s102 MiB [] 28% 1.5s102 MiB [] 29% 1.4s102 MiB [] 30% 1.4s102 MiB [] 31% 1.4s102 MiB [] 32% 1.3s102 MiB [] 33% 1.3s102 MiB [] 34% 1.3s102 MiB [] 35% 1.3s102 MiB [] 36% 1.2s102 MiB [] 37% 1.2s102 MiB [] 38% 1.2s102 MiB [] 40% 1.1s102 MiB [] 41% 1.1s102 MiB [] 42% 1.1s102 MiB [] 43% 1.1s102 MiB [] 44% 1.0s102 MiB [] 45% 1.0s102 MiB [] 46% 1.0s102 MiB [] 47% 1.0s102 MiB [] 47% 1.1s102 MiB [] 49% 1.1s102 MiB [] 50% 1.0s102 MiB [] 52% 1.0s102 MiB [] 53% 0.9s102 MiB [] 54% 0.9s102 MiB [] 56% 0.8s102 MiB [] 57% 0.8s102 MiB [] 59% 0.8s102 MiB [] 61% 0.7s102 MiB [] 63% 0.7s102 MiB [] 64% 0.7s102 MiB [] 65% 0.6s102 MiB [] 66% 0.6s102 MiB [] 67% 0.6s102 MiB [] 68% 0.6s102 MiB [] 69% 0.6s102 MiB [] 70% 0.6s102 MiB [] 71% 0.6s102 MiB [] 72% 0.5s102 MiB [] 74% 0.5s102 MiB [] 75% 0.5s102 MiB [] 76% 0.4s102 MiB [] 77% 0.4s102 MiB [] 78% 0.4s102 MiB [] 79% 0.4s102 MiB [] 80% 0.4s102 MiB [] 81% 0.4s102 MiB [] 83% 0.3s102 MiB [] 84% 0.3s102 MiB [] 85% 0.3s102 MiB [] 86% 0.3s102 MiB [] 87% 0.3s102 MiB [] 89% 0.2s102 MiB [] 90% 0.2s102 MiB [] 91% 0.2s102 MiB [] 92% 0.2s102 MiB [] 93% 0.1s102 MiB [] 95% 0.1s102 MiB [] 96% 0.1s102 MiB [] 98% 0.0s102 MiB [] 99% 0.0s102 MiB [] 100% 0.0s
WebKit 26.5 (playwright webkit v2336) downloaded to /root/.cache/ms-playwright/webkit-2336
Downloading FFmpeg (playwright ffmpeg v1011) from https://cdn.playwright.dev/dbazure/download/playwright/builds/ffmpeg/1011/ffmpeg-linux.zip
2.3 MiB [] 0% 0.0s2.3 MiB [] 3% 0.6s2.3 MiB [] 6% 0.6s2.3 MiB [] 13% 0.4s2.3 MiB [] 20% 0.3s2.3 MiB [] 28% 0.2s2.3 MiB [] 45% 0.1s2.3 MiB [] 69% 0.1s2.3 MiB [] 97% 0.0s2.3 MiB [] 100% 0.0s
FFmpeg (playwright ffmpeg v1011) downloaded to /root/.cache/ms-playwright/ffmpeg-1011
Playwright Host validation warning:
╔══════════════════════════════════════════════════════╗
║ Host system is missing dependencies to run browsers. ║
║ Please install them with the following command:      ║
║                                                      ║
║     playwright install-deps                          ║
║                                                      ║
║ Alternatively, use apt:                              ║
║     apt-get install libgtk-3-0t64                    ║
║                                                      ║
║ <3 Playwright Team                                   ║
╚══════════════════════════════════════════════════════╝
    at validateDependenciesLinux (/usr/local/lib/python3.13/dist-packages/playwright/driver/package/lib/coreBundle.js:31846:9)
    at async Registry._validateHostRequirements (/usr/local/lib/python3.13/dist-packages/playwright/driver/package/lib/coreBundle.js:33280:18)
    at async Registry._validateHostRequirementsForExecutableIfNeeded (/usr/local/lib/python3.13/dist-packages/playwright/driver/package/lib/coreBundle.js:33402:11)
    at async Registry.validateHostRequirementsForExecutablesIfNeeded (/usr/local/lib/python3.13/dist-packages/playwright/driver/package/lib/coreBundle.js:33391:11)
    at async installBrowsers (/usr/local/lib/python3.13/dist-packages/playwright/driver/package/lib/coreBundle.js:69417:5)
    at async _Command.<anonymous> (/usr/local/lib/python3.13/dist-packages/playwright/driver/package/lib/coreBundle.js:72930:7)
Installing dependencies...
Get:1 https://dl.google.com/linux/chrome-stable/deb stable InRelease [2,548 B]
Get:2 https://cli.github.com/packages stable InRelease [4,685 B]
Get:3 https://cloud.r-project.org/bin/linux/ubuntu noble-cran40/ InRelease [3,631 B]
Get:4 http://security.ubuntu.com/ubuntu noble-security InRelease [126 kB]
Get:5 https://r2u.stat.illinois.edu/ubuntu noble InRelease [9,161 B]
Get:6 https://dl.google.com/linux/chrome-stable/deb stable/main amd64 Packages [1,409 B]
Hit:7 http://archive.ubuntu.com/ubuntu noble InRelease
Get:8 https://cloud.r-project.org/bin/linux/ubuntu noble-cran40/ Packages [72.4 kB]
Get:9 http://archive.ubuntu.com/ubuntu noble-updates InRelease [126 kB]
Hit:10 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu noble InRelease
Get:11 https://r2u.stat.illinois.edu/ubuntu noble/main all Packages [10.2 MB]
Get:12 http://security.ubuntu.com/ubuntu noble-security/restricted amd64 Packages [1,796 kB]
Get:13 http://security.ubuntu.com/ubuntu noble-security/universe amd64 Packages [1,530 kB]
Get:14 http://security.ubuntu.com/ubuntu noble-security/main amd64 Packages [1,242 kB]
Get:15 https://r2u.stat.illinois.edu/ubuntu noble/main amd64 Packages [2,990 kB]
Get:16 http://archive.ubuntu.com/ubuntu noble-backports InRelease [126 kB]
Get:17 http://archive.ubuntu.com/ubuntu noble-updates/universe amd64 Packages [2,151 kB]
Get:18 http://archive.ubuntu.com/ubuntu noble-updates/restricted amd64 Packages [1,913 kB]
Get:19 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 Packages [1,565 kB]
Fetched 23.8 MB in 3s (9,339 kB/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu noble InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libasound2t64 is already the newest version (1.2.11-1ubuntu0.3).
libasound2t64 set to manually installed.
libatk-bridge2.0-0t64 is already the newest version (2.52.0-1build1).
libatk-bridge2.0-0t64 set to manually installed.
libatk1.0-0t64 is already the newest version (2.52.0-1build1).
libatk1.0-0t64 set to manually installed.
libatspi2.0-0t64 is already the newest version (2.52.0-1build1).
libatspi2.0-0t64 set to manually installed.
libcairo2 is already the newest version (1.18.0-3build1).
libcairo2 set to manually installed.
libcups2t64 is already the newest version (2.4.7-1.2ubuntu7.14).
libcups2t64 set to manually installed.
libdbus-1-3 is already the newest version (1.14.10-4ubuntu4.1).
libdbus-1-3 set to manually installed.
libdrm2 is already the newest version (2.4.125-1ubuntu0.1~24.04.2).
libdrm2 set to manually installed.
libgbm1 is already the newest version (25.2.8-0ubuntu0.24.04.2).
libgbm1 set to manually installed.
libglib2.0-0t64 is already the newest version (2.80.0-6ubuntu3.8).
libglib2.0-0t64 set to manually installed.
libnspr4 is already the newest version (2:4.35-1.1build1).
libnspr4 set to manually installed.
libnss3 is already the newest version (2:3.98-1ubuntu0.2).
libnss3 set to manually installed.
libpango-1.0-0 is already the newest version (1.52.1+ds-1build1).
libpango-1.0-0 set to manually installed.
libx11-6 is already the newest version (2:1.8.7-1build1).
libx11-6 set to manually installed.
libxcb1 is already the newest version (1.15-1ubuntu2).
libxcb1 set to manually installed.
libxcomposite1 is already the newest version (1:0.4.5-1build3).
libxcomposite1 set to manually installed.
libxdamage1 is already the newest version (1:1.1.6-1build1).
libxdamage1 set to manually installed.
libxext6 is already the newest version (2:1.3.4-1build2).
libxfixes3 is already the newest version (1:6.0.0-2build1).
libxfixes3 set to manually installed.
libxkbcommon0 is already the newest version (1.6.0-1build1).
libxkbcommon0 set to manually installed.
libxrandr2 is already the newest version (2:1.5.2-2build1).
libxrandr2 set to manually installed.
libavcodec60 is already the newest version (7:6.1.1-3ubuntu5).
libavcodec60 set to manually installed.
libcairo-gobject2 is already the newest version (1.18.0-3build1).
libcairo-gobject2 set to manually installed.
libfontconfig1 is already the newest version (2.15.0-1.1ubuntu2).
libfreetype6 is already the newest version (2.13.2+dfsg-1ubuntu0.1).
libfreetype6 set to manually installed.
libgdk-pixbuf-2.0-0 is already the newest version (2.42.10+dfsg-3ubuntu3.3).
libgdk-pixbuf-2.0-0 set to manually installed.
libpangocairo-1.0-0 is already the newest version (1.52.1+ds-1build1).
libpangocairo-1.0-0 set to manually installed.
libx11-xcb1 is already the newest version (2:1.8.7-1build1).
libx11-xcb1 set to manually installed.
libxcb-shm0 is already the newest version (1.15-1ubuntu2).
libxcb-shm0 set to manually installed.
libxcursor1 is already the newest version (1:1.2.1-1build1).
libxcursor1 set to manually installed.
libxi6 is already the newest version (2:1.8.1-1build1).
libxi6 set to manually installed.
libxrender1 is already the newest version (1:0.9.10-1.1build1).
libicu74 is already the newest version (74.2-1ubuntu3.1).
libicu74 set to manually installed.
libatomic1 is already the newest version (14.2.0-4ubuntu2~24.04.1).
libatomic1 set to manually installed.
libepoxy0 is already the newest version (1.5.10-1build1).
libepoxy0 set to manually installed.
libevent-2.1-7t64 is already the newest version (2.1.12-stable-9ubuntu2.1).
libevent-2.1-7t64 set to manually installed.
libflite1 is already the newest version (2.2-6build3).
libflite1 set to manually installed.
libgles2 is already the newest version (1.7.0-1build1).
libgstreamer1.0-0 is already the newest version (1.24.2-1ubuntu0.1).
libgstreamer1.0-0 set to manually installed.
libgtk-4-1 is already the newest version (4.14.5+ds-0ubuntu0.10).
libgtk-4-1 set to manually installed.
libharfbuzz0b is already the newest version (8.3.0-2build2).
libharfbuzz0b set to manually installed.
libjpeg-turbo8 is already the newest version (2.1.5-2ubuntu2).
libjpeg-turbo8 set to manually installed.
liblcms2-2 is already the newest version (2.14-2ubuntu0.1).
liblcms2-2 set to manually installed.
libopus0 is already the newest version (1.4-1build1).
libopus0 set to manually installed.
libpng16-16t64 is already the newest version (1.6.43-5ubuntu0.6).
libpng16-16t64 set to manually installed.
libvpx9 is already the newest version (1.14.0-1ubuntu2.3).
libvpx9 set to manually installed.
libwayland-client0 is already the newest version (1.22.0-2.1build1).
libwayland-client0 set to manually installed.
libwayland-egl1 is already the newest version (1.22.0-2.1build1).
libwayland-egl1 set to manually installed.
libwebp7 is already the newest version (1.3.2-0.4build3).
libwebp7 set to manually installed.
libwebpdemux2 is already the newest version (1.3.2-0.4build3).
libxml2 is already the newest version (2.9.14+dfsg-1.3ubuntu3.8).
libxml2 set to manually installed.
libxslt1.1 is already the newest version (1.1.39-0exp1ubuntu0.24.04.3).
libx264-164 is already the newest version (2:0.164.3108+git31e19f9-1).
libx264-164 set to manually installed.
xvfb is already the newest version (2:21.1.12-1ubuntu1.6).
fonts-liberation is already the newest version (1:2.1.5-3).
The following additional packages will be installed:
  dictionaries-common emacsen-common glib-networking glib-networking-common
  glib-networking-services hunspell-en-us libaa1 libabsl20220623t64

In [4]:
import nest_asyncio
nest_asyncio.apply()

from playwright.async_api import async_playwright
import asyncio

async def scrape_with_playwright():
    async with async_playwright() as p:

        browser = await p.chromium.launch(headless=True) #launch chromium headless browser
        page = await browser.new_page()

        print("playwright: opening page..")
        await page.goto("https://quotes.toscrape.com/scroll")

        await page.wait_for_selector('.quote')

        print("playwright: ccrolling to trigger dynamic load..")

        await page.evaluate("window.scrollTo(0, document.body.scrollHeight)")

        await page.wait_for_function("document.querySelectorAll('.quote').length > 10")

        quotes = await page.query_selector_all('.quote')
        print(f"Playwright: successfully loaded {len(quotes)} quotes after scrolling")

        print("\nsample quotes extracted via playwright:")
        for i in range(2):
            text_element = await quotes[i].query_selector('.text')
            text = await text_element.inner_text()
            print(f"- {text}")

        await browser.close()

asyncio.run(scrape_with_playwright())

playwright: opening page..
playwright: ccrolling to trigger dynamic load..
Playwright: successfully loaded 20 quotes after scrolling

sample quotes extracted via playwright:
- “The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”
- “It is our choices, Harry, that show what we truly are, far more than our abilities.”

**Scraping Methodology**



***Question 1: Static Web Scraping***

for this part i used requests and beautifulsoup. To find the elements i opened chrome developer tools and right clicked to inspect the page. At first i was clicking the wrong things and targeting the wrong div so my lists were coming up empty. It took me a while to realize i had to target the article tag with the class product_pod to actually get the books. For navigation my code looks for the li tag with the class next and extracts the link to go to the next page. The program knows it is finished when it searches for that next button and returns nothing so it just breaks the loop. to verify my data i made the scraper grab the total expected results from the page and compare it to my actual scraped count at the end of each category.  





**Question 2: Dynamic Web Scraping**

For the dynamic page i first checked with requests and found 0 quotes in the HTML which proved i needed selenium. Navigating the page meant using a javascript command to scroll to the bottom of the page. For the waits i used WebDriverWait instead of time.sleep() because the assignment required explicit waits. it waits until the count of quote elements on the page strictly increases. My program decides it is completely done when it tries to scroll and wait but no new quotes load for two consecutive times.
i faced a lot of challenges here. first i tried to run the code but got a NameError because i forgot to import the webdriver stuff. then when i added the imports i got a ModuleNotFoundError because i didn't realize i had to actually pip install selenium in colab before using it. i thought it was just already there like pandas. i fixed it by adding the install commands in a cell above. to verify the data i checked the csv to make sure the scroll batches incremented properly and there were no duplicates.  




**Bonus: Playwright**

I also tried the playwright bonus. My main challenge was setting it up because it required different install commands and i had to use nest_asyncio to make it work inside the colab environment. for the comparison playwright felt easier to wait for elements because of its auto waiting features compared to selenium.